### ISSUE TITLE
## App setup

### ISSUE THREAD

**Issue by nacirabogenschneider** [nacirabogenschneider/capstone-project#1]
# Value statement

As a developer I need to structur my project

# Description (Text, Scribble, Wireframe, Design)

Set up app structur and configuration

# Tasks

- [ ] create-react-app
- [ ] create Git repository
- [ ] connect Git repository
- [ ] install needed packages
- [ ] .prettierrc
- [ ] .gitignore
- [ ] package.json
- [ ] Google fonts
- [ ] icon libary
- [ ] global Styles

# Size

small
