### ISSUE TITLE
## Main Sections in App

### ISSUE THREAD

**Issue by nacirabogenschneider** [nacirabogenschneider/capstone-project#2]
# Value statement
As a parent, I would like to have an overview of the primary schools in my city and which corresponding school route meeting points already exist.

# Description (Text, Scribble, Wireframe, Design)
It is a map on which all primary schools in Germany are listed.

# Acceptance criteria
- [ ] Get the schools.json from the other project
- [ ] Integrate the Google Maps API into the React project
- [ ] Create necessary components for the Google Map

# Tasks
- [ ] Component Map
- [ ] Function filterSchoolData 
- [ ] General styling 
- [ ] Test filter function 

# Size
medium
