### ISSUE TITLE
## Insert Google Maps API

### ISSUE THREAD

**Issue by nacirabogenschneider** [nacirabogenschneider/capstone-project#3]
# Value statement

As a parent I would like to have an overview of the primary schools in Germany on a map.

# Description (Text, Scribble, Wireframe, Design)

It is a map on which all primary schools in Germany are marked.

# Acceptance criteria

- [ ] Create Google Developer Profile
- [ ] Create API Key
- [ ] Embed API in
- [ ] Change Maps style
- [ ] Include Maps Marker
- [ ] Show all primary schools in germany

# Tasks

- [ ] Insert Google Map API
- [ ] Function renderSchoolData
- [ ] Add Marker

# Size
medium
