### ISSUE TITLE
Add an animated counter for all children per class.

### ISSUE THREAD

**Issue by nacirabogenschneider** [nacirabogenschneider/capstone-project#32]
# Description

As a parent I what to see how many childen go into the school

# Acceptance criteria

- [x] Show the children per class for every school

# Tasks

- [x] Install react spring 
- [x] add the Data for every school
- [x] animate a counter per class 

# Size

medium
